name: monorepo-matrix
description: Checks monorepo changes
author: Blazej Maciaszek
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  build-all:
    description: "Build all services"
    required: false
    default: "false"
  map:
    description: "Map paths to service names"
    required: true
    default: ""
outputs:
  result:
    description: "Result of the check"
